### ISSUE TITLE
Convert from Personal to Organizational Github

### ISSUE THREAD

**Issue by camthegeek** [aeonix/aeon#71]
Hello,

I have talked with several other people throughout the community and have found many issues with AEON's current structure. Our focus for this issue will be converting the Github account that AEON uses from a personal user account controlled by one into an organizational github account which can be controlled by many. I do believe this issue is one of the easiest to fix. Personally, I would love to move the funding system repository to the AEON Github (As well as other projects).

**Why an organizational account?**
TLDR: With this type of account, the main admin would be able to assign other admins and users to certain repo's and more. We would not be left wondering if the account maintainer was struck by lightning causing the project to come to a halt. For more information on roles: https://help.github.com/articles/repository-permission-levels-for-an-organization/

Outside of user roles and the whole bus factor, the organizational structure would give more credibility to those who are looking to improve AEON's presence across a multitude of sources such as but not limited to: forums, exchanges, services, commerce providers, etc.. 

Currently, the community lacks the ability to create AEON related documents, files, sites, etc and have them stored on the official AEON github. Everything links to an outside repository in which it's also controlled by a single account who may or may not be able to merge changes. Not many are great with git services, coding or have the desire to fork and maintain a project. By placing on the official AEON repo, it becomes a center for anything AEON to become updated by anyone.

If we are to be a community driven coin, I strongly believe that opening our Github up as an organization and assigning users to repositories would be a great step in the right direction for being more community driven. 

edit 1: Link to instructions on how to convert: https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by shigutso** [comment]
I totally agree with that. AEON should have more trusted devs around (with proper permissions, of course), pushing the development even further.

**Comment by 420coupe** [comment]
Definitely agree AEON should be turned into an organization to allow others to contribute and continue the forward progression with AEON.

**Comment by BigslimVdub** [comment]
Being that Aeon was forked to become a community driven project, having a sole entity controlling the project results in the opposite of the original purpose. 
I do trust that the Aeonix admin could appropriately position members to maintain areas of the project that he does not have time for. This would result in a more flowing approach to bug resolution and project advancement.

**Comment by DeadManWalkingTO** [comment]
I believe that this will be in the right direction.

**Comment by stoffu** [comment]
Overall I don't see much point in this proposal.

@camthegeek 
> Currently, the community lacks the ability to create AEON related documents, files, sites, etc and have them stored on the official AEON github.

The current maintainer (@iamsmooth == @aeonix) has been able to incorporate any proposed changes to the CLI/GUI/website repos as long as they're reasonable and supported by the community. I don't know what "issues" there are. Can you list specific problematic cases if any?

@BigslimVdub 
> Being that Aeon was forked to become a community driven project, having a sole entity controlling the project results in the opposite of the original purpose.

I disagree. Monero is also purely community driven. Aeon was forked from Monero just because someone decided to do so, not because Monero became centralized and ceased to be community-driven. Write accesses to the Monero repositories are held by the Monero Core Team members AFAIK, but most of the time the repos are updated (i.e. merging PRs) by @fluffypony and @luigi1111. @fluffypony used to be updating all of the CLI/GUI/website repos, but as he became more and more busy over time, @luigi1111 came to be the succeeding maintainer for the GUI and the website repos (he also updates the CLI repo sometimes).

Some people often criticize Monero as centralized due to the repos being maintained by the Core Team, which is a flawed argument. The way Aeon resources are maintained is exactly the same as in Monero, and I don't see any problem here.

**Comment by shigutso** [comment]
@stoffu the issue is, at the current state, Aeon's github repo has write access by only one account that is controlled by only one person, which defeats the purpose of being a decentralized, community-driven project.

Of course, if something happens to @iamsmooth or @aeonix we can fork it and move on, but I think it would be better if the community could have some kind of control on the official channels. For example, the subreddit has a few mods, so even if katiecharm goes away (which seems pretty much like it nowadays), we know that we can count on someone if we need something. I think that a bit of decentralized control is good for the community if handled correctly, so why not?

**Comment by stoffu** [comment]
I still don’t understand. I haven’t seen any instance where smooth is blocking anyone’s pull request.

**Comment by shigutso** [comment]
"If something happens to smooth" can mean many things, the most common example is "if he is hit by a bus". But literally anything can happen and we have no control (besides forking and moving on). That's one of the disadvantages of keeping the power centralized. Maybe Monero wouldn't be as big as it is today if fluffypony was the only user with write access to Monero's repo, but that's just my opinion as a user of Aeon.

**Comment by BigslimVdub** [comment]
If the president of a country dies, does the country collapse into uncertainty or do other elected officials take over to continue control?

Also, I see that people may believe giving merging control may allow unwanted changes to the code base. On the flip side those with no merging control may believe that their ideas will not be taken seriously because they are never merged.

As said before, I believe smooth could assign appropriate control to members willing to responsibly control those privileges.

I don’t know personal relationships between all current and past contributors, but I forsee a good future ahead.

**Comment by fluffypony** [comment]
If ya’ll don’t agree with something smooth does then just fork the repo and provide an alternate implementation.

**Comment by camthegeek** [comment]
The idea was to have someone else around to create repo's on request for the community. This was not limited to core/gui/website changes.

For the community, there is an organization setup in which we will be turning it into a collection of repositories related to AEON. See github.com/aeoncommunity/ -- those who want access can request. Members can make their own repo's inside of there

Some want to see this change here, some do not. Some have even failed to read the original post in full and missed the whole point. Thanks for your input (to the few who kept it relevant). The community based organization makes this issue obsolete. I am closing this issue.

**Comment by bobbieltd** [comment]
@camthegeek  and @shigutso : Both of you are really good guys. I see that you both are trying to make AEON stronger. HOWEVER Aeon is not only little brother but also competitor of Monero. There is a conflit of interest between Aeon and Monero. Don’t expect too much from core devs.

**Comment by bobbieltd** [comment]
Monero devs are VERY professional. They are very careful at any changes for Aeon. Changes can create exploits/bugs.
Everything is on the table. It is how crypto works. When community get divided, they fork and create a new coin (like what happened with Bitcoin). No one wants that but it is a good mechanism.
